### ISSUE TITLE
System.PlatformNotSupportedException: The system's ping utility could not be found

### ISSUE THREAD

**Issue by Steve0212a** [georg-jung/ArpLookup#20]
I am creating a custom module for Azure IoT Edge (running linux) and would like to use your utility to lookup mac addresses.  However, I am getting the following exception inside the docker linux container:

```
System.Net.NetworkInformation.PingException: An exception occurred during a Ping request.
 ---> System.PlatformNotSupportedException: The system's ping utility could not be found.
   at System.Net.NetworkInformation.Ping.GetPingProcess(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendWithPingUtilityAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsyncInternal(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
   --- End of inner exception stack trace ---
   at System.Net.NetworkInformation.Ping.SendPingAsyncInternal(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
   at ArpLookup.LinuxLookupService.PingThenTryReadFromArpTableAsync(IPAddress ip, TimeSpan timeout)
   at ArpLookup.Arp.LookupAsync(IPAddress ip)
   at <my code here>
```

As you can see, the ping is failing from System.Net (your IsSupported returns true).  However, when I go to look up the MAC Address, I have already contacted the device using SNMP, so the MAC address is already in the arp table.  I have confirmed the MAC Address is in the file even though ping is not working.

Can you please provide a method to do the lookup in the arp table without calling ping first?  Another option would be to catch the exception from System.Net.Ping and check the arp table anyway in case communication was already established.

Thanks.

**Comment by georg-jung** [comment]
The method you are asking for already exists [here](https://github.com/georg-jung/ArpLookup/blob/affa6eb18c703b03d5c41daf59890fb977746bac/src/ArpLookup/LinuxLookupService.cs#L91), but it is internal because I don't think making that API public would be beneficial.

The behaviour of ArpLookup however should already support your usecase: [Looking at the relevant code](https://github.com/georg-jung/ArpLookup/blob/affa6eb18c703b03d5c41daf59890fb977746bac/src/ArpLookup/Arp.cs#L42) shows that the library first checks the arp table, only pings on failure and then checks it again. Thus, your address either is not in the arp table before the ping attempt or it wouldn't be found without the ping attempt either.

Could you provide some more information on this, such as the addresses and a relevant copy of your `/proc/net/arp` file to look furhter into this?

If you don't want to provide the addresses you might be able to directly debug into the library's code, as we do provide symbol packages on nuget and support sourcelink, so that you might be able to reproduce and track down the problem on your own.

**Comment by Steve0212a** [comment]
Naturally, I am not trying to reproduce the issue and I cannot.  I am not sure what caused the issue, but it appears to be working now.  Thanks.
