### ISSUE TITLE
Mac Address is null for existing interface

### ISSUE THREAD

**Issue by yoyos** [georg-jung/ArpLookup#30]
Hello,

Mac Address is null even if /proc/net/arp is installed
I'm testing on Linux ubuntu with ArpLookup 2.0.3
Am I doing something wrong for linux ? (This code works on windows)

Thanks !

```
val_admin@esxi-US2004:~/$ uname -a
Linux esxi-US2004 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

val_admin@esxi-US2004:~/$ sudo ./TestConsole
MacAddress is null for address: 172.16.20.157

val_admin@esxi-US2004:~/$ sudo cat /proc/net/arp
IP address       HW type     Flags       HW address            Mask     Device
172.16.23.254    0x1         0x2         00:1a:8c:f0:c5:c8     *        ens160
172.16.20.1      0x1         0x2         00:1d:d8:b7:1c:15     *        ens160

val_admin@esxi-US2004:~/$ sudo ifconfig
ens160: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.20.157  netmask 255.255.252.0  broadcast 172.16.23.255
        inet6 fe80::20c:29ff:fe42:496e  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:42:49:6e  txqueuelen 1000  (Ethernet)
        RX packets 153382  bytes 995851464 (995.8 MB)
        RX errors 0  dropped 7188  overruns 0  frame 0
        TX packets 127770  bytes 12066629 (12.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 200  bytes 18132 (18.1 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 200  bytes 18132 (18.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

val_admin@esxi-US2004:~/$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0c:29:42:49:6e brd ff:ff:ff:ff:ff:ff
    inet 172.16.20.157/22 brd 172.16.23.255 scope global ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe42:496e/64 scope link
       valid_lft forever preferred_lft forever


```

Used code :

```csharp
PhysicalAddress? macAddress = null;
IPAddress? ipAddress = IPAddress.Parse("172.16.20.157");

if (!Arp.IsSupported)
    Console.WriteLine("Platform is not supported");

if (ipAddress is null)
    Console.WriteLine("Client IpAddress not found");
else
    macAddress = await Arp.LookupAsync(ipAddress);

if (macAddress is null)
    Console.WriteLine("MacAddress is null for address: " + ipAddress);
```

**Comment by georg-jung** [comment]
Hi, thanks for your contribution and providing the PR.

While I didn't test myself on ubuntu, I agree with you that it will probably not work to use ArpLookup to find the mac address for a local nic by IP. This is not what ArpLookup is made for though. The intention of ArpLookup is to find the mac addresses of _other devices/nics_ on the same network by IP, but not the mac addresses of the local nics.

While it might work to achieve that by parsing the ip addr command's output, I think ArpLookup is the wrong place to add such code. I consider mac address lokups for _local_ vs _remote_ nics a quite different use case in that regard. Also, you would call one method than which contains code for both, first look for a remote nic, than for a local one. I think that behaviour could be rather confusing for other users.

There is however a quite simple way to achieve your desired behaviour - even without ArpLookup or any other dependecies. Please try the following code. I tested it on windows, it should be cross platform though.

    using System.Net;
    using System.Net.NetworkInformation;

    foreach(
        var nic in NetworkInterface
        .GetAllNetworkInterfaces()
        .Where(nic => nic.OperationalStatus == OperationalStatus.Up && nic.NetworkInterfaceType != NetworkInterfaceType.Loopback)
        )
    {
        var ips = nic.GetIPProperties().UnicastAddresses.Where(adr => adr.Address.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork).Select(adr => adr.Address.ToString());
        Console.WriteLine($"{string.Join(", ", ips)} {nic.GetPhysicalAddress()} {nic.Name}");
    }

    Console.WriteLine("----------------");

    // get hwaddr for one IP
    var ip = IPAddress.Parse("172.16.20.157");

    var nic2 = NetworkInterface
        .GetAllNetworkInterfaces()
        .Where(nic => nic.OperationalStatus == OperationalStatus.Up && nic.NetworkInterfaceType != NetworkInterfaceType.Loopback)
        .Where(nic => nic.GetIPProperties().UnicastAddresses.Any(adr => adr.Address.Equals(ip)))
        .FirstOrDefault();

    Console.WriteLine($"HWAddr for IP {ip} is {nic2?.GetPhysicalAddress()?.ToString() ?? "UNKNOWN"}");

For further information see also this [StackOverflow thread](https://stackoverflow.com/q/850650/1200847).

If I misunderstood your intention or if you there is anything further to improve or fix about ArpLookup please let me know. Id otherwise close the issue and PR if I correctly understood your use case and the above information works for you.

**Comment by yoyos** [comment]
Hello, you're right there is another way without ArpLookup but the lib was working with local addresses on windows so I thought it was a bug that it was not working the same on Linux

You decide if you want to add my feature but in any case I think it's a nice fall back in case arp isn't working.

Sometimes you don't know if the input is your ip or not, so I think it's best to always gives the Mac address, even for local IP.

**Comment by georg-jung** [comment]
I still think that mac address lokups for local vs remote nics are a quite different use case. Thus, I prefer the clarity that `Lookup` does remote lookups and also the simplicity of the existing code. I think mixing the local and remote use case might be confusing to consumers, also considering the library has _arp_ in its name, which is exactly about remote lookups but never about local ones.

I might reconsider if there are more requests and/or explanations of real world use case where the local nic functionality would make sense. I'd then still prefer an implementation that does not depend on any external processes: It might be impossible to execute them, the output format might change, the current implementation isn't async.

I agree with you that others might look for this functionality, which is why I added a [corresponding section to the README](https://github.com/georg-jung/ArpLookup/blob/bf69eaaee16d9a03cb5feb2fe25f5414e56332f2/README.md#local-nics-mac-addresses).

Thanks again for your thoughts and your contribution!
